---
# tasks file for ansible-libapex
- name: Install libapex dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - libglib2.0-dev
      - libgirepository1.0-dev
      - libjson-glib-dev
      - libprotobuf-c-dev
      - libzmq3-dev
      - libczmq-dev
      - meson
      - valac

- name: Clone libapex
  git:
    repo: https://gitlab.com/crdc/apex/libapex
    dest: /usr/src/libapex
    force: yes

- name: Build libapex
  shell: |
    cd /usr/src/libapex
    meson -Dshared-lib=true -Dprefix=/usr _build
    ninja -C _build
    ninja -C _build install
